name: chat_gpt1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    name: merge-test
    
    runs-on: ubuntu-latest #어느 운영체제에서 job을 실행할지 지정합니다.
    defaults:
        run:         
          working-directory: ./server
# job의 명령어가 동작하는 기본 디렉토리를 설정한다.
# 리포지토리에서 빌드하기위한 gradlew 파일이 /server 안에 위치하고 있었기 때문에 위와 같이 설정하였다.

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: write KEY
      run: echo " API_KEY =${{secrets.API_KEY}}" >> env.yml
      working-directory: ./github
